### ISSUE TITLE
Unsupported chunks: minf, elm1, regn, umid, DGDA - AVID related

### ISSUE THREAD

**Issue by mercuryswitch** [MediaArea/BWFMetaEdit#163]
<img width="1363" alt="Screen Shot 2020-07-21 at 8 55 08 pm" src="https://user-images.githubusercontent.com/47848559/88047229-a742e980-cb94-11ea-9864-97672664aaf2.png">

Not sure if this is an issue or an enhancement, but something I noted when using Pro Tools in the past, I got the unsupported chunks error, is that something that could be added? We had issues with these files but the information was useless to anyone other than Avid. I imagine many are using Pro Tools. Also a date format issue. Thanks!

**Comment by dericed** [comment]
Perhaps the wording should be changed so that this is less alarming, but I'd say it's info rather than an error. BWF MetaEdit does what other wav readers should do and just skips over the chunks that it isn't designed to interpret, but here we list them out as unsupported (by BWF MetaEdit) so that the user can at least have the knowledge that they are there.

**Comment by MarcosSueiro** [comment]
A very useful feature may be to `--strip-all-unsupported-chunks` ...it always worries me to have extraneous data swishing around inside the wav files

**Comment by dericed** [comment]
I feel cautious about this as it would be a destructive process. Perhaps in the unsupported chunks list we could add a method to overwrite the chunk with the 'junk' or 'skip' chunk with a lot of warnings. What sorts of unsupported chunks do you wish to exile from the wav?

**Comment by MarcosSueiro** [comment]
I agree about the warnings, but otoh I feel BWFME has other destructive processes... (e.g. IART="").

The image below is (sigh) fairly typical for our legacy files:

![image](https://user-images.githubusercontent.com/521684/198735434-0e6cbacc-d015-4aa9-9d31-75063d3c544e.png)

**Comment by JeromeMartinez** [comment]
> I feel BWFME has other destructive processes... (e.g. IART="").

It is not wanted, please open a ticket with more info about that.

**Comment by MarcosSueiro** [comment]
No ticket needed Jerôme --I just meant that from the CLI one can erase data (albeit not entire chunks of course)

**Comment by JeromeMartinez** [comment]
> I  just meant that from the CLI one can erase data (albeit not entire chunks of course)

I see better.
But in that case, it is an explicit choice to remove a specific itme (actually to replace it with empty value).
Saying "Delete everything not recognized" is another level, especially when what is deleted may change depending on the version (if version n+1 recognizes a field, it is no more deleted).
I think that I prefer an option to delete a specific field even if unknown, e.g. ` --delete=levl`, and another option e.g. ` --reject-if-unknwon` which would make an error if a new unknown field is found and then you manually check the chunk and explicitely add it to the list of chunks to delete, so you know what you delete instead of just ignoring (it really may be dangerous if you get later a very important chunk but forgot the "delete all unknown chunks" option).

**Comment by g-maxime** [comment]
Maybe, in this case, an "--remove-chunks=name" option instead of blindly remove all unknown chunks.
With a little scripting, removing all the unwanted chunks will be easy.

**Comment by MarcosSueiro** [comment]
Yeah, you guys are right... a `--delete=levl ` or `--remove-chunks=name` etc option would be helpful methinks.
