### ISSUE TITLE
CodingHistory rules do not recognize A=ANALOG

### ISSUE THREAD

**Issue by EricJacobsTAA** [MediaArea/BWFMetaEdit#252]
BWF MetaEdit 21.07 (MacOS 10.13.6)

BEXT Chunk - CodingHistory rules do not recognize "A=ANALOG"

Allowed:
A=ANALOGUE,M=stereo,T=Nakamichi CR7A; SNA130-13566;compact cassette

"Malformed input" error/flag:
A=ANALOG,M=stereo,T=Nakamichi CR7A; SNA130-13566;compact cassette

**Comment by JeromeMartinez** [comment]
`ANALOG` is not valid with [EBU R98-1999](https://tech.ebu.ch/docs/r/r098.pdf), it is `ANALOGUE`.
I am not in favor of accepting `ANALOG` for EBU R98 check because it is synonym of `ANALOGUE` and `ANALOGUE` could be used if EBU R98 compatibility is wanted, @kmurmur what do you think about that?

but... We see in [FADGI doc](https://www.digitizationguidelines.gov/audio-visual/documents/BWF_Embed_Guideline_v3_2021.pdf) `Coding Algorithm <ANALOG, PCM, MPEG1L1, MPEG1L2, MPEG1L3, MPEG2L1, MPEG2L2, MPEG2L3>` (so difference between FADGI and EBU, same liste except `ANALOG` vs `ANALOGUE`) **but** with examples having sometimes something different ("Analogue" is also seen). @kmurmur please indicate the exact rule for Coding History "A" field, is `Coding Algorithm <ANALOG, PCM, MPEG1L1, MPEG1L2, MPEG1L3, MPEG2L1, MPEG2L2, MPEG2L3>` the only acceptable values (so a file can not be EBU R98 and FADGI compatible if analog), or is any upper/lowercase and with or without "ue" accepted by FADGI? Currently we accept only `ANALOGUE` even when FADGI rule is selected.

**Comment by kmurmur** [comment]
@JeromeMartinez thanks for the question. Honestly, I suspect that I put in "ANALOG" (US spelling) as an unintended default. It is also ANALOG in the previous versions of the Guidelines. The "ANALOGUE" examples are new to version 3 though so I can certainly see where the confusion is. 

In this particular case, I don't think we need to vary from R98 so it might be good to 1) stick with ANALOGUE and 2) issue a errata to fix the Guidelines. 

@EricJacobsTAA - how problematic is this for you in your workflows?

**Comment by JeromeMartinez** [comment]
> In this particular case, I don't think we need to vary from R98 so it might be good to 1) stick with ANALOGUE and 2) issue a errata to fix the Guidelines.

I am in favor of that, also FADGI recommendations extends EBU R98 without conflicting with it.
Especially because this is the first time we catch this inconsistency in FADGI doc so people use to have `ANALOGUE`.

**Comment by EricJacobsTAA** [comment]
@kmurmer and @JeromeMartinez - Short answer, ANALOGUE may be awkward for some clients, but certainly not a workflow problem.  Having an EBU BWF "linter" available is more valuable than a spelling adjustment.

Longer answer - I'd like to expand the use of BWFMetaEdit both in-house and among clients.  There are currently thousands of files that contain ANALOG since the bulk of our clients are in North America and we were following FADGI with the US variant instead of the UK variant.  Going forward we will use and advise A=ANALOGUE.

Without going too far astray, the "F=any value" bug (#251) is a workflow problem when documenting resampling in CodingHistory.

**Comment by JeromeMartinez** [comment]
I suggest to have a pause on this ticket until we resolve https://github.com/MediaArea/BWFMetaEdit/issues/251.

**Comment by JeromeMartinez** [comment]
@EricJacobsTAA please test [latest development snapshots](https://mediaarea.net/download/snapshots/binary/).
