### ISSUE TITLE
FR: in-core-csv= command

### ISSUE THREAD

**Issue by X-Raym** [MediaArea/BWFMetaEdit#39]
Hi,

Currently, there is `in-core=` which add metadata from the specified Core file, and all the individual possibilities (`in-core-Description=` etc...).

It would be nice to have `in-core-csv=`, which could set metadata from a CSV string (and not a file). This way, if we have to set up multiples metadata, no need to call bwfmetaedit several times, or to dump the metadata as file first.

This function could update only specified file for eg:

```CSV
Description,Loudness
This is my file,-4
```

Would only add the Description and Loudness fields.

or we could simply pass a single CSV line which would override any values (in this cases, pre-processing to add metadata values which needs to be preserved have to be done from a script).

What do you think about it ? :)

Cheers !

**Comment by JeromeMartinez** [comment]
I tested:

```
bwfmetaedit sample.wav' --Description=test --Originator=test2
```

and the 2 fields are filled.
So if I understand well, you prefer to have that in the form

```
bwfmetaedit sample.wav' --in-core-csv=Description,Originator\r\ntest,test2
```

instead of the the multi-parameters form or CSV file input, right?

This is "just" another way to provide input, this is possible but will not be a priority as IMO there is already an interface (actually 2: command line direct input and CSV file) for providing several values without the need to call BWFMetaEdit several times nor dump metadata first (you can use your CSV example as file input, without the other metadata).

Note: I didn't use "LoudnessValue" on the command line because looks like there is a bug (option rejected), but the following CSV (in a file) works:
```
FileName,Description,Originator,LoudnessValue
.\sample.wav,Desc3,Orig3,-3
```

Note 2: BWF MetaEdit is currently not actively maintained (we mainly provide bug fixes for bugs considered as important for our [sponsors](https://mediaarea.net/SupportUs)), so no ETA.

**Comment by X-Raym** [comment]
Thanks for your quick answer !
I didn't realized that we could chain argument, so I can use that indeed 👍  It will work just as good. We may close the issue then.

> Note 2: BWF MetaEdit is currently not actively maintained

Ok ! Though, as it is open source, it worth reporting features anyway, maybe others can be interested by proposing a pull request :)

Thanks again !
