### ISSUE TITLE
design a single-file-form view

### ISSUE THREAD

**Issue by dericed** [MediaArea/BWFMetaEdit#79]
From earlier discussions, BWF MetaEdit currently presents all edit and review in a series of tables but there's no single form in the ui to see all details of one file. I propose design of such a form which the same field components as the tables but arranged in a form which shows the contents of the chunks for review and edit.

**Comment by dericed** [comment]
@JeromeMartinez, can you up my permissions here, I can't assign @ablwr directly

**Comment by JeromeMartinez** [comment]
> @JeromeMartinez, can you up my permissions here, I can't assign @ablwr directly

She was not in the list of collaborators for this project, done, you can assign her now.

**Comment by ablwr** [comment]
:wave:

**Comment by dericed** [comment]
The assignment still isn't working but I gather than @ablwr knows O_O

**Comment by ablwr** [comment]
I am ONLINE

**Comment by ablwr** [comment]
Okay, this is intentionally not styled, but the idea I have is something like this --

![Screenshot from 2020-02-14 17-12-19](https://user-images.githubusercontent.com/3260492/74572713-917a2a00-4f4d-11ea-9918-f296a57d3d9b.png)

The technical data does not have to take the same shape as things that can be edited, so it can reasonably fit to be condensed on one line.

The BEXT fields are using their fuller name, with the ability to hover over them to get the more technical four-letter code and a definition of what that code is (similar to how BWF MetaEdit works now when you hover -- I didn't code this up for the above/below demo, though). I think it makes more sense to use the human-readable name, especially for newer users.


I made a [gist](https://gist.github.com/ablwr/e45b3242faead7552b0e54d4cb0940aa) because the boxes flow out based on the size of the screen, so everyone can be able to see everything on the screen, regardless of they are on a 11" laptop or super-4k-triple-monitor kind of situation. You can save that gist on your computer and open it up to play around with the size and how it changes in the browser window. My browser is set at a fairly normal screen size.

I also currently have commented-out a few optional features like MD5 and UMID. If they were checked, and likewise for any of these fields being unchecked or if there are Errors/Information/UnsupportedChunks fields, they would either show up or not show up.

**Comment by JeromeMartinez** [comment]
OK, so as I understand it we could show this UI in another selectable "view", with maybe a drop-down list for the list of files, and we put it as the default view; user would select the other "views" if comparing files is wanted.

**Comment by ablwr** [comment]
I imagine it repeating per file but being able to condense each section (similar to how in MediaConch you can click to show/hide parts of a policy) -- I forgot to mention that part!

**Comment by JeromeMartinez** [comment]
Closed by https://github.com/MediaArea/BWFMetaEdit/pull/87, @ablwr reopen it if/when you have comments about the new UI.
